title:  config.yml
author: Suptrung
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Site that will include the programs and the other file for this project 
Theme: minima 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
